### ISSUE TITLE
Little more help 

### ISSUE THREAD

**Issue by access3424** [kbilicic/kb-lua-framework#1]
Hi,

Could you provide some guidance on how to use this?

**Comment by kbilicic** [comment]
I’ll do my best to make it by end of the week

**Comment by kbilicic** [comment]
I need some more time to make this work better since sometimes I still get memory issues on Q X7
I'll do my best to post an update in here, if not video then text definitely

**Comment by kbilicic** [comment]
I made some updates to the current version, I'll put in more details once I make the changes I have planned. Mostly fixing all the bugs
